freebsd_instance:
  image: freebsd-12-0-release-amd64

main_task:
  script:
    - echo "Hello cirrus"
    - ls
    - yes | pkg install cmake
    - which cmake
    - which cc
    - which c++
    - cc --version
    - c++ --version