freebsd_instance:
  image: freebsd-12-0-release-amd64

main_task:
  script:
    - echo "Hello cirrus"
    - ls
    - yes | pkg install cmake
    - cc --version
    - c++ --version

    # Basic c build
    - cd lib 
    - cc -Wall -Wextra -Werror --std=gnu89 -DFT_CONGIG_HAVE_WCHAR fort.c -c -o fort.o 
    - rm fort.o 
    - cd .. 

    # Basic c++ build
    - cd lib 
    - cp fort.c fort.cpp
    - c++ -Wall -Wextra -Werror -DFT_CONGIG_HAVE_WCHAR fort.cpp -c -o fort.o 
    - rm fort.o 
    - cd .. 