language: C
sudo: required # to prevent fail of executables build with clang and sanitizers
matrix:
  include:
    - os: linux
      compiler: gcc
      env: GCC_BUILD=ON
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --build-root build --include src --include tests  --gcov-options '\-lp'
    - os: linux
      compiler: clang
      env: GCC_BUILD=OFF



script:
  # Print all environment variables to aid in CI development
  - printenv
  # Print version and available CMake generators to aid in CI development
  - cmake --version

  # Build cmocka
  - mkdir -p tests/cmocka-1.1.0/build
  - cd tests/cmocka-1.1.0/build
  - cmake ..
  - make
  - cd ../../..

  # Perform out-of-source build(CMake backend generation, build, and test)
  # Test build without optimizations
  - mkdir -p build
  - cd build
  - cmake .. -DFORT_TEST_BUILD=ON -DFORT_GCC_BUILD=${GCC_BUILD} 
  - cmake --build . --target all 
  - ls
  - LSAN_OPTIONS=verbosity=1:log_threads=1 ./libfort_dummy
  - LSAN_OPTIONS=verbosity=1:log_threads=1 ./libfort_example
  - LSAN_OPTIONS=verbosity=1:log_threads=1 ./libfort_test


